{% set name = "tinymist" %}
{% set version = "0.12.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Myriad-Dreamin/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 69755c0b6561d18517361a9d90c636ba95f18e32bb23cd752f5658657189c340

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - tinymist --version

about:
  home: https://github.com/Myriad-Dreamin/tinymist
  summary: 'An integrated language service for Typst.'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
