{% set name = "tinymist" %}
{% set version = "0.13.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Myriad-Dreamin/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65a5f90297ed89652802993d0b4b9504b2b5ec2b54fd23935b48976301a046d7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - tinymist --version

about:
  home: https://github.com/Myriad-Dreamin/tinymist
  summary: 'An integrated language service for Typst.'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
