{% set name = "tinymist" %}
{% set version = "0.13.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Myriad-Dreamin/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 164dfeb3495f4ccc5c99e5db6003b5f1c7a1561e40ad9ad0abed258e7e478ff4

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - tinymist --version

about:
  home: https://github.com/Myriad-Dreamin/tinymist
  summary: 'An integrated language service for Typst.'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
