{% set name = "tinymist" %}
{% set version = "0.11.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Myriad-Dreamin/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 877d0c3722ac863d5f6f6469bd8b7b9a7ee461a2e4f50310ed0d42b795c1f182

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - tinymist --version

about:
  home: https://github.com/Myriad-Dreamin/tinymist
  summary: 'An integrated language service for Typst.'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
