schema_version: 1

context:
  name: tinymist
  version: 0.14.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Myriad-Dreamin/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 36cf8b0714ef918daa626c27c9b6d2add7d6ce741323bf51cfa29f455a707ba2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tinymist --version

about:
  summary: An integrated language service for Typst.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/Myriad-Dreamin/tinymist

extra:
  recipe-maintainers:
    - freundTech
