schema_version: 1

context:
  name: tinymist
  version: "0.14.25"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Myriad-Dreamin/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b0f91cab6f389b3a885882bba3cd6523bd8982f5d096262e9d58770c7bf532c2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tinymist --version

about:
  summary: An integrated language service for Typst.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/Myriad-Dreamin/tinymist

extra:
  recipe-maintainers:
    - freundTech
