schema_version: 1

context:
  name: tinymist
  version: "0.15.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Myriad-Dreamin/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 03d49413dd70d06d670d3c1970b4a416201ca6076bc4a321d4ffbce9893096ee

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tinymist --version

about:
  summary: An integrated language service for Typst.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/Myriad-Dreamin/tinymist

extra:
  recipe-maintainers:
    - freundTech
