schema_version: 1

context:
  name: tinymist
  version: "0.15.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Myriad-Dreamin/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 5dfdc9b055e39d4e645d778747b0e24a3395afaeb835603bfba8db9286a552cb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tinymist --version

about:
  summary: An integrated language service for Typst.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/Myriad-Dreamin/tinymist

extra:
  recipe-maintainers:
    - freundTech
